###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2024. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################

# Release Details
DATE = "2024-09-05"
RELEASE = "IBM FileNet Content Manager 5.6.0-LA004"

# Repository Details
VERSION = "5.6.0-LA004"
APP_VERSION = "24.0.0"

# OLM Version Details
CHANNEL = "v24.0"
CSV = "v56.0.1-2"




