###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2024. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################

# ####################################################
# ##            Registry Authentication             ##
# ####################################################

# Key used to authenticate with IBM Entitlement Registry
# Check the link on how to obtain an IBM Entitlement key https://www.ibm.com/docs/SSNW2F_5.6.0/com.ibm.dba.install/op_topics/tsk_images_enterp_entitled.html
ENTITLEMENT_KEY = "<IBMEntitlementKey>"

# CNCF Only: Pull images from a pirvate registry
# OCP deployment, use Airgap deployment method
PRIVATE_REGISTRY_HOST = "<RegistryHost>"

PRIVATE_REGISTRY_PORT = 5000

PRIVATE_REGISTRY_USERNAME = "<RegistryUser>"

PRIVATE_REGISTRY_PASSWORD = "<RegistryPassword>"

# Is your private registry using SSL - Valid values: [true; false]
PRIVATE_REGISTRY_SSL_ENABLED = true

# File Path to the ssl cert of the private registry
# Required Field only if PRIVATE_REGISTRY_SSL_ENABLED is true
# Cerificates needs to in PEM format
PRIVATE_REGISTRY_SSL_CRT_PATH = "/path/to/crt/certificate.pem"