# ####################################################
# ##           Common Database Properties           ##
# ####################################################

# Provide the database type from your infrastructure.
DATABASE_TYPE = "sqlserver"

# The parameter is used to support database connection over SSL for database.
DATABASE_SSL_ENABLE = false

# ####################################################
# ##         Property Section for GCD database      ##
# ####################################################

[GCD]

# Datasource name for the database.
DATASOURCE_NAME = "FNGCDDS"

# Datasource XA name for the database.
DATASOURCE_NAME_XA = "FNGCDDSXA"

# Provide the database server name or IP address of the database server.
DATABASE_SERVERNAME = "10.0.0.72"

# Provide the database server port.
DATABASE_PORT = "1433"

# Provide the name of the database
DATABASE_NAME = "fngcd"

# Provide the username of the database.
DATABASE_USERNAME = """fngcd"""

# Provide the password of the database.
DATABASE_PASSWORD = """P@ssw0rd"""

# ####################################################
# ##         Property Section for OS database      ##
# ####################################################

[OS]

# Label of the Object Store.
OS_LABEL = "os"

# Datasource name for the database.
DATASOURCE_NAME = "FNOS1DS"

# Datasource XA name for the database.
DATASOURCE_NAME_XA = "FNOS1DSXA"

# Provide the database server name or IP address of the database server.
DATABASE_SERVERNAME = "10.0.0.72"

# Provide the database server port.
DATABASE_PORT = "1433"

# Provide the name of the database
DATABASE_NAME = "fnos"

# Provide the username of the database.
DATABASE_USERNAME = """fnos"""

# Provide the password of the database.
DATABASE_PASSWORD = """P@ssw0rd"""

# ####################################################
# ##         Property Section for ICN database      ##
# ####################################################

[ICN]

# Datasource name for the database.
DATASOURCE_NAME = "ECMClientDS"

# Provide the database server name or IP address of the database server.
DATABASE_SERVERNAME = "10.0.0.72"

# Provide the database server port.
DATABASE_PORT = "1433"

# Provide the name of the database
DATABASE_NAME = "fnicn"

# Provide the username of the database.
DATABASE_USERNAME = """fnicn"""

# Provide the password of the database.
DATABASE_PASSWORD = """P@ssw0rd"""

# Tablespace name for the database.
TABLESPACE_NAME = "ICNDB"

# Schema name for the database.
SCHEMA_NAME = "ICNDB"
