apiVersion: 'v1'
kind: 'Secret'
metadata:
  name: 'ibm-fncm-secret'
type: 'Opaque'
stringData:
  ltpaPassword: 'P@ssw0rd'
  keystorePassword: 'P@ssw0rdDataserve2030'
  appLoginUsername: 'p8admin'
  appLoginPassword: 'P@ssw0rd'
  gcdDBUsername: 'fngcd'
  gcdDBPassword: '{xor}Dx8sLChvLTs='
  osDBUsername: 'fnos'
  osDBPassword: '{xor}Dx8sLChvLTs='
